Fix integration env for CircleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -6,7 +6,7 @@ commands:
     parameters:
       sbt_version:
         type: string
-        default: "1.3.8"
+        default: "1.3.9"
     steps:
       - run:
           name: Setup SBT
@@ -16,6 +16,25 @@ commands:
                       curl --silent -L -o sbt.tgz https://piccolo.link/sbt-<< parameters.sbt_version >>.tgz
                       tar -xzvf sbt.tgz && rm -f sbt.tgz
                     fi
+
+  setup_integration:
+    description: Setup integration environment
+    steps:
+      - run:
+          name: Prepare integration environment
+          command: |
+                    if [ `which make | wc -l` -eq 0 ]; then
+                      sudo apt update
+                      sudo apt install build-essential
+                    fi
+                    ./.ci_scripts/beforeInstall.sh
+
+      - run:
+          name: Start integration services
+          command: |
+                    export MONGO_CONF="/tmp/mongod.conf"
+                    ./.ci_scripts/fork-mongod.sh /tmp/validate-env.sh
+          background: true
 
   build_n_tests:
     description: Build & Run tests
@@ -39,6 +58,18 @@ commands:
                       -print -exec cp {} test-reports \;
           when: always
 
+  update_cache:
+    description: Update cache
+    steps:
+      - save_cache:
+          paths:
+            - ~/.ivy2
+            - ~/.coursier/cache
+            - ~/.sbt
+            - ~/sbt
+            - ~/mongodb-linux-x86_64-amazon-4.2.2
+            - ~/ssl
+          key: d-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
 
 jobs:
   jdk10_scala211:
@@ -57,18 +88,14 @@ jobs:
 
       - restore_cache:
           keys:
-          - jdk10_scala211-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
+          - d-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
           - dependencies-
+
+      - setup_integration
 
       - build_n_tests
 
-      - save_cache:
-          paths:
-            - $HOME/.ivy2
-            - $HOME/.coursier/cache
-            - $HOME/.sbt
-            - $HOME/sbt
-          key: jdk10_scala211-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
+      - update_cache
 
       - collect_test_reports
       - store_test_results:
@@ -90,22 +117,36 @@ jobs:
 
       - restore_cache:
           keys:
-          - jdk8_scala212-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
+          - d-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
           - dependencies-
+
+      - setup_integration
 
       - build_n_tests
 
-      - save_cache:
-          paths:
-            - $HOME/.ivy2
-            - $HOME/.coursier/cache
-            - $HOME/.sbt
-            - $HOME/sbt
-          key: jdk8_scala212-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
+      - update_cache
 
       - collect_test_reports
       - store_test_results:
           path: test-reports
+
+      - deploy:
+          name: Publish artifacts to Sonatype Snapshots
+          command: |
+                    if [ ! "${CIRCLE_BRANCH}" = "master" ]; then
+                      echo "Skipped on branch ${CIRCLE_BRANCH}"
+                      exit 0
+                    fi
+                    
+                    export PUBLISH_REPO_ID="oss.sonatype.org"
+                    export PUBLISH_REPO_URL="https://oss.sonatype.org/content/repositories/snapshots"
+                    
+                    if [ "x$PUBLISH_USER" = "x" -o "x$PUBLISH_PASS" = "x" ]; then
+                      echo "Missing publication credentials"
+                      exit 1
+                    fi
+                    
+                    sbt +publish
 
   jdk9_scala213:
     docker:
@@ -123,18 +164,14 @@ jobs:
 
       - restore_cache:
           keys:
-          - jdk9_scala213-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
+          - d-{{ .Environment.CIRCLE_JOB }}-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
           - dependencies-
+
+      - setup_integration
 
       - build_n_tests
 
-      - save_cache:
-          paths:
-            - $HOME/.ivy2
-            - $HOME/.coursier/cache
-            - $HOME/.sbt
-            - $HOME/sbt
-          key: jdk9_scala213-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
+      - update_cache
 
       - collect_test_reports
       - store_test_results:
@@ -143,15 +180,15 @@ jobs:
 workflows:
   version: 2
 
-  scala_2_11:
+  jdk10_scala211:
     jobs:
       - jdk10_scala211
 
-  scala_2_12:
+  jdk8_scala212:
     jobs:
       - jdk8_scala212
 
-  scala_2_13:
+  jdk9_scala213:
     jobs:
       - jdk9_scala213
 
